const modules=[['dashboard','Dashboard','Pregled mrežne infrastrukture'],['dns','DNS','PowerDNS zone i zapisi'],['dhcp','DHCP','Kea subneti, rezervacije i leaseovi'],['certificates','Certificates','Step CA i javni ACME certifikati'],['proxy','Reverse Proxy','Nginx aplikacije i TLS'],['monitoring','Monitoring','Zdravlje servisa i upozorenja'],['backup','Backup','Sigurne kopije i povrat podataka'],['mail','Mail','SMTP alarmi i agregacija događaja'],['users','Users','Korisnici, MFA i ovlasti'],['audit','Audit log','Evidencija administratorskih promjena']];
const $=s=>document.querySelector(s); let current='dashboard';
function csrfToken(){const m=document.cookie.match(/(?:^|;\s*)saguaro_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):''}
async function api(path,options={}){const headers={'Content-Type':'application/json'};const method=(options.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){headers['X-CSRF-Token']=csrfToken()}const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});if(r.status===401){showLogin();throw Error('Prijava je istekla.')}const body=await r.json();if(!r.ok)throw Error(body.error||'Greška zahtjeva');return body}
function showLogin(){$('#login').classList.remove('hidden');$('#shell').classList.add('hidden')}
function showShell(){$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');renderNav();openModule(current)}
function renderNav(){const nav=$('#nav');nav.innerHTML='';for(const [id,name] of modules){const b=document.createElement('button');b.textContent=name;b.className=id===current?'active':'';b.onclick=()=>openModule(id);nav.appendChild(b)}}
async function openModule(id){current=id;renderNav();const m=modules.find(x=>x[0]===id);$('#title').textContent=m[1];$('#description').textContent=m[2];$('#content').innerHTML='<div class="panel muted">Učitavanje…</div>';try{id==='dashboard'?await dashboard():id==='audit'?await audit():id==='monitoring'?await monitoring():id==='mail'?await mailPage():id==='dns'?await dnsPage():id==='dhcp'?await dhcpPage():id==='users'?await usersPage():await modulePage(id)}catch(e){$('#content').innerHTML=`<div class="panel error">${escapeHtml(e.message)}</div>`}}
async function dashboard(){const [d,services]=await Promise.all([api('/api/dashboard'),api('/api/services')]);$('#content').innerHTML=`<div class="cards"><div class="card"><div class="muted">Servisi</div><div class="metric">${d.services}</div></div><div class="card"><div class="muted">Konfigurirano</div><div class="metric">${d.configured}</div></div><div class="card"><div class="muted">Zdravo</div><div class="metric">${d.healthy}</div></div><div class="card"><div class="muted">Upozorenja</div><div class="metric">${d.alerts}</div></div></div><div class="panel"><h2>Komponente</h2><div class="services">${services.map(s=>`<div class="card service"><div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p></div><div><div class="status">${escapeHtml(s.status)}</div><button onclick="checkService('${s.id}')">Provjeri</button></div></div>`).join('')}</div></div>`}
async function checkService(id){try{const r=await api(`/api/services/${id}/actions/check`,{method:'POST',body:'{}'});alert(`${r.result.id}: ${r.result.status}\n${r.result.detail||''} (${r.result.latencyMs} ms)`);openModule(current)}catch(e){alert(e.message)}}
async function modulePage(id){const details={dns:['Zone i zapisi','U idućem milestoneu: forward/reverse zone, DNSSEC, ACL i validirani reload.'],dhcp:['Kea DHCP','Subneti, poolovi, rezervacije, KNOWN/UNKNOWN/DROP klase i quarantine politike.'],certificates:['Upravljanje certifikatima','Step CA za internu PKI te ACME/Let’s Encrypt za javne domene.'],proxy:['Nginx aplikacije','Deklarativni virtual hosts, TLS, WebSocket i rollback nakon nginx -t provjere.'],monitoring:['Monitoring','Servisi, resursi, DHCP poolovi, DNS greške i certifikati pred istekom.'],backup:['Backup','Šifrirane kopije, retention, provjera integriteta i restore test.'],users:['Korisnici i uloge','Planirane uloge: admin, network-operator, dns-operator, auditor i read-only.']}[id];$('#content').innerHTML=`<div class="panel"><h2>${details[0]}</h2><p class="muted">${details[1]}</p><p>Modul je registriran u GUI-ju; CRUD adapter dolazi u sljedećem koraku.</p></div>`}
async function monitoring(){const rows=await api('/api/events?limit=100');$('#content').innerHTML=`<div class="panel"><h2>Događaji (zadnjih ${rows.length})</h2><table><thead><tr><th>Vrijeme</th><th>Razina</th><th>Modul</th><th>Akcija</th><th>Poruka</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td>${escapeHtml(x.severity)}</td><td>${escapeHtml(x.module)}</td><td>${escapeHtml(x.action||'')}</td><td>${escapeHtml(x.message)}</td></tr>`).join('')}</tbody></table></div>`}
const ROLES=['admin','network-operator','dns-operator','auditor','read-only'];
async function usersPage(){const me=await api('/api/profile');let list=null;try{list=await api('/api/users')}catch(e){list=null}
const mine=`<div class="panel"><h2>Moj račun</h2><p>Korisnik: <b>${escapeHtml(me.username)}</b> — uloga: <b>${escapeHtml(me.role)}</b></p>
<form id="pwForm" class="stack"><h3>Promjena lozinke</h3><label>Trenutna lozinka <input id="pwOld" type="password" required></label><label>Nova lozinka (min. 14 znakova) <input id="pwNew" type="password" minlength="14" required></label><div><button type="submit">Promijeni</button></div><div id="pwMsg" class="muted"></div></form></div>`;
const admin=list===null?'':`<div class="panel"><h2>Korisnici (${list.length})</h2><table><thead><tr><th>Korisnik</th><th>Uloga</th><th>Aktivan</th><th></th></tr></thead><tbody>${list.map(u=>`<tr><td>${escapeHtml(u.username)}</td><td><select class="uRole" data-u="${escapeHtml(u.username)}">${ROLES.map(r=>`<option ${r===u.role?'selected':''}>${r}</option>`).join('')}</select></td><td>${u.enabled?'da':'ne'}</td><td><button class="uToggle" data-u="${escapeHtml(u.username)}" data-e="${u.enabled?1:0}">${u.enabled?'Onemogući':'Omogući'}</button> <button class="uReset" data-u="${escapeHtml(u.username)}">Reset lozinke</button> <button class="uDel" data-u="${escapeHtml(u.username)}">Obriši</button></td></tr>`).join('')}</tbody></table>
<form id="uAdd" class="stack"><h3>Novi korisnik</h3><label>Korisničko ime <input id="uName" required></label><label>Lozinka (min. 14) <input id="uPass" type="password" minlength="14" required></label><label>Uloga <select id="uNewRole">${ROLES.map(r=>`<option>${r}</option>`).join('')}</select></label><div><button type="submit">Dodaj</button></div><div id="uMsg" class="muted"></div></form></div>`;
$('#content').innerHTML=mine+admin;
$('#pwForm').onsubmit=async e=>{e.preventDefault();$('#pwMsg').textContent='';try{await api('/api/profile/password',{method:'POST',body:JSON.stringify({oldPassword:$('#pwOld').value,newPassword:$('#pwNew').value})});$('#pwMsg').textContent='Lozinka promijenjena.';$('#pwOld').value='';$('#pwNew').value=''}catch(err){$('#pwMsg').textContent=err.message}};
if(list===null)return;
const patch=async(u,body)=>{try{await api(`/api/users/${encodeURIComponent(u)}`,{method:'PATCH',body:JSON.stringify(body)});usersPage()}catch(err){alert(err.message)}};
document.querySelectorAll('.uRole').forEach(el=>el.onchange=()=>patch(el.dataset.u,{role:el.value}));
document.querySelectorAll('.uToggle').forEach(el=>el.onclick=()=>patch(el.dataset.u,{enabled:el.dataset.e!=='1'}));
document.querySelectorAll('.uReset').forEach(el=>el.onclick=()=>{const p=prompt(`Nova lozinka za ${el.dataset.u} (min. 14 znakova):`);if(p)patch(el.dataset.u,{password:p})});
document.querySelectorAll('.uDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati korisnika ${el.dataset.u}?`))return;try{await api(`/api/users/${encodeURIComponent(el.dataset.u)}`,{method:'DELETE'});usersPage()}catch(err){alert(err.message)}});
$('#uAdd').onsubmit=async e=>{e.preventDefault();$('#uMsg').textContent='';try{await api('/api/users',{method:'POST',body:JSON.stringify({username:$('#uName').value.trim(),password:$('#uPass').value,role:$('#uNewRole').value})});usersPage()}catch(err){$('#uMsg').textContent=err.message}}}
let dnsZone=null;
async function dnsPage(){const zones=await api('/api/dns/zones');
$('#content').innerHTML=`<div class="panel"><h2>Zone (${zones.length})</h2><table><thead><tr><th>Zona</th><th>Vrsta</th><th>Serial</th><th></th></tr></thead><tbody>${zones.map(z=>`<tr><td><a href="#" class="zoneLink" data-z="${escapeHtml(z.name)}">${escapeHtml(z.name)}</a></td><td>${escapeHtml(z.kind)}</td><td>${z.serial||''}</td><td><button class="zoneDel" data-z="${escapeHtml(z.name)}">Obriši</button></td></tr>`).join('')}</tbody></table>
<form id="zoneAdd" class="stack"><h3>Nova zona</h3><label>Naziv <input id="zName" placeholder="example.internal" required></label><label>Nameserveri (zarezom) <input id="zNs" placeholder="ns1.example.internal" required></label><div><button type="submit">Dodaj zonu</button></div><div id="zMsg" class="muted"></div></form></div><div id="zoneDetail"></div>`;
document.querySelectorAll('.zoneLink').forEach(el=>el.onclick=e=>{e.preventDefault();openZone(el.dataset.z).catch(err=>alert(err.message))});
document.querySelectorAll('.zoneDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati zonu ${el.dataset.z}? Zapisi se brišu iz PowerDNS-a.`))return;try{await api(`/api/dns/zones/${encodeURIComponent(el.dataset.z)}`,{method:'DELETE'});dnsZone=null;dnsPage()}catch(err){alert(err.message)}});
$('#zoneAdd').onsubmit=async e=>{e.preventDefault();$('#zMsg').textContent='';try{await api('/api/dns/zones',{method:'POST',body:JSON.stringify({name:$('#zName').value.trim(),nameservers:$('#zNs').value.split(',').map(s=>s.trim()).filter(Boolean)})});dnsPage()}catch(err){$('#zMsg').textContent=err.message}};
if(dnsZone)await openZone(dnsZone)}
async function openZone(name){dnsZone=name;const d=await api(`/api/dns/zones/${encodeURIComponent(name)}`);const hidden=['SOA','RRSIG','NSEC','NSEC3','NSEC3PARAM','DNSKEY','CDS','CDNSKEY'];const sets=(d.rrsets||[]).filter(s=>!hidden.includes(s.type));
$('#zoneDetail').innerHTML=`<div class="panel"><h2>Zapisi — ${escapeHtml(name)}</h2><table><thead><tr><th>Ime</th><th>Tip</th><th>TTL</th><th>Vrijednosti</th><th></th></tr></thead><tbody>${sets.map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.type)}</td><td>${s.ttl}</td><td>${escapeHtml((s.records||[]).map(r=>r.content).join(', '))}</td><td><button class="recDel" data-n="${escapeHtml(s.name)}" data-t="${escapeHtml(s.type)}">Obriši</button></td></tr>`).join('')}</tbody></table>
<form id="recAdd" class="stack"><h3>Dodaj / uredi zapis</h3><label>Ime (FQDN) <input id="rName" placeholder="host.${escapeHtml(name)}" required></label><label>Tip <select id="rType">${['A','AAAA','CNAME','TXT','MX','SRV','NS','PTR','CAA'].map(t=>`<option>${t}</option>`).join('')}</select></label><label>TTL <input id="rTtl" type="number" value="3600" min="1"></label><label>Vrijednosti (zarezom) <input id="rVal" placeholder="192.168.10.20" required></label><div><button type="submit">Spremi zapis</button></div><div id="rMsg" class="muted"></div></form></div>`;
document.querySelectorAll('.recDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati ${el.dataset.n} ${el.dataset.t}?`))return;try{await api(`/api/dns/zones/${encodeURIComponent(name)}/records`,{method:'PUT',body:JSON.stringify({name:el.dataset.n,type:el.dataset.t,delete:true,ttl:0,contents:[]})});openZone(name)}catch(err){alert(err.message)}});
$('#recAdd').onsubmit=async e=>{e.preventDefault();$('#rMsg').textContent='';try{await api(`/api/dns/zones/${encodeURIComponent(name)}/records`,{method:'PUT',body:JSON.stringify({name:$('#rName').value.trim(),type:$('#rType').value,ttl:parseInt($('#rTtl').value,10)||3600,contents:$('#rVal').value.split(',').map(s=>s.trim()).filter(Boolean),delete:false})});openZone(name)}catch(err){$('#rMsg').textContent=err.message}}}
async function dhcpPage(){const get=p=>api(p).catch(e=>({err:e.message}));const [subnets,leases,resv]=await Promise.all([get('/api/dhcp/subnets'),get('/api/dhcp/leases'),get('/api/dhcp/reservations')]);
const sub=subnets.err?`<p class="muted">${escapeHtml(subnets.err)}</p>`:`<table><thead><tr><th>ID</th><th>Subnet</th><th>Poolovi</th><th></th></tr></thead><tbody>${subnets.map(s=>`<tr><td>${s.id}</td><td>${escapeHtml(s.subnet)}</td><td>${escapeHtml((s.pools||[]).join(', '))}</td><td><button class="subEdit" data-id="${s.id}" data-subnet="${escapeHtml(s.subnet)}" data-pool="${escapeHtml((s.pools||[])[0]||'')}">Uredi</button> <button class="subDel" data-id="${s.id}">Obriši</button></td></tr>`).join('')}</tbody></table>`;
const subForm=`<form id="subForm" class="stack"><h3 id="subFormTitle">Novi subnet</h3><input type="hidden" id="subId" value="">
<label>Subnet (CIDR) <input id="subCidr" placeholder="192.168.20.0/24" required></label>
<label>Pool od <input id="subPoolStart" placeholder="192.168.20.100" required></label>
<label>Pool do <input id="subPoolEnd" placeholder="192.168.20.200" required></label>
<label>Router (gateway) <input id="subRouter" placeholder="192.168.20.1"></label>
<label>DNS serveri (zarezom) <input id="subDns" placeholder="192.168.20.1"></label>
<label>Domena <input id="subDomain" placeholder="example.internal"></label>
<div><button type="submit">Spremi subnet</button> <button type="button" id="subReset">Poništi</button></div>
<p class="muted">Promjena ide kroz transakciju: config-test → config-set → provjera → config-write (uz automatski rollback na grešku).</p>
<div id="subMsg" class="muted"></div></form>`;
const lea=leases.err?`<p class="muted">${escapeHtml(leases.err)}</p>`:`<table><thead><tr><th>IP</th><th>MAC</th><th>Hostname</th><th>Subnet</th><th>Istječe</th></tr></thead><tbody>${leases.map(l=>`<tr><td>${escapeHtml(l.ip)}</td><td>${escapeHtml(l.mac)}</td><td>${escapeHtml(l.hostname||'')}</td><td>${l.subnetId}</td><td>${l.expires?new Date(l.expires*1000).toLocaleString():''}</td></tr>`).join('')}</tbody></table>`;
const res=resv.err?`<p class="muted">${escapeHtml(resv.err)}</p>`:`<table><thead><tr><th>IP</th><th>MAC</th><th>Hostname</th><th>Subnet</th><th></th></tr></thead><tbody>${resv.map(x=>`<tr><td>${escapeHtml(x.ip)}</td><td>${escapeHtml(x.mac)}</td><td>${escapeHtml(x.hostname||'')}</td><td>${x.subnetId}</td><td><button class="resDel" data-id="${x.id}">Obriši</button></td></tr>`).join('')}</tbody></table>`;
const subOpts=subnets.err?'<option value="1">1</option>':subnets.map(s=>`<option value="${s.id}">${s.id} — ${escapeHtml(s.subnet)}</option>`).join('');
$('#content').innerHTML=`<div class="panel"><h2>Subneti</h2>${sub}${subForm}</div><div class="panel"><h2>Aktivni leaseovi (${leases.err?'—':leases.length})</h2>${lea}</div><div class="panel"><h2>Rezervacije</h2>${res}
<form id="resAdd" class="stack"><h3>Nova rezervacija</h3><label>MAC <input id="resMac" placeholder="aa:bb:cc:dd:ee:ff" required></label><label>IP <input id="resIp" placeholder="192.168.10.50" required></label><label>Hostname <input id="resHost"></label><label>Subnet <select id="resSub">${subOpts}</select></label><div><button type="submit">Dodaj rezervaciju</button></div><div id="resMsg" class="muted"></div></form></div>`;
const subPayload=()=>({subnet:$('#subCidr').value.trim(),poolStart:$('#subPoolStart').value.trim(),poolEnd:$('#subPoolEnd').value.trim(),router:$('#subRouter').value.trim(),domain:$('#subDomain').value.trim(),dnsServers:$('#subDns').value.split(',').map(s=>s.trim()).filter(Boolean)});
$('#subForm').onsubmit=async e=>{e.preventDefault();$('#subMsg').textContent='Primjena…';const id=$('#subId').value;try{if(id){await api(`/api/dhcp/subnets/${id}`,{method:'PUT',body:JSON.stringify(subPayload())})}else{await api('/api/dhcp/subnets',{method:'POST',body:JSON.stringify(subPayload())})}dhcpPage()}catch(err){$('#subMsg').textContent=err.message}};
$('#subReset').onclick=()=>{$('#subId').value='';$('#subFormTitle').textContent='Novi subnet';['subCidr','subPoolStart','subPoolEnd','subRouter','subDns','subDomain'].forEach(i=>$('#'+i).value='');$('#subCidr').disabled=false};
document.querySelectorAll('.subEdit').forEach(el=>el.onclick=()=>{$('#subId').value=el.dataset.id;$('#subFormTitle').textContent=`Uredi subnet ${el.dataset.subnet} (ID ${el.dataset.id})`;$('#subCidr').value=el.dataset.subnet;$('#subCidr').disabled=true;const p=(el.dataset.pool||'').split('-').map(s=>s.trim());$('#subPoolStart').value=p[0]||'';$('#subPoolEnd').value=p[1]||'';$('#subMsg').textContent='CIDR se ne mijenja — za promjenu CIDR-a obrišite pa dodajte subnet.'});
document.querySelectorAll('.subDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati subnet ID ${el.dataset.id}? DHCP za taj segment prestaje raditi.`))return;try{await api(`/api/dhcp/subnets/${el.dataset.id}`,{method:'DELETE'});dhcpPage()}catch(err){if(err.message.includes('force=true')&&confirm(err.message+'\n\nObrisati zajedno s rezervacijama?')){try{await api(`/api/dhcp/subnets/${el.dataset.id}?force=true`,{method:'DELETE'});dhcpPage()}catch(e2){alert(e2.message)}}else{alert(err.message)}}});
document.querySelectorAll('.resDel').forEach(el=>el.onclick=async()=>{if(!confirm('Obrisati rezervaciju?'))return;try{await api(`/api/dhcp/reservations/${el.dataset.id}`,{method:'DELETE'});dhcpPage()}catch(err){alert(err.message)}});
$('#resAdd').onsubmit=async e=>{e.preventDefault();$('#resMsg').textContent='';try{await api('/api/dhcp/reservations',{method:'POST',body:JSON.stringify({mac:$('#resMac').value.trim(),ip:$('#resIp').value.trim(),hostname:$('#resHost').value.trim(),subnetId:parseInt($('#resSub').value,10),id:0})});$('#resMsg').textContent='Rezervacija dodana — aktivna je za nove DHCP zahtjeve.';dhcpPage()}catch(err){$('#resMsg').textContent=err.message}}}
async function mailPage(){const m=await api('/api/mail');const sev=['info','notice','warning','error','critical','security'];$('#content').innerHTML=`<div class="panel"><h2>SMTP postavke</h2><form id="mailForm" class="stack">
<label>Server <input id="mHost" value="${escapeHtml(m.host||'')}" placeholder="smtp.smtp2go.com" required></label>
<label>Port <input id="mPort" type="number" value="${m.port||587}" min="1" max="65535" required></label>
<label>TLS <select id="mTls">${['starttls','tls','none'].map(t=>`<option ${t===m.tlsMode?'selected':''}>${t}</option>`).join('')}</select></label>
<label>From <input id="mFrom" type="email" value="${escapeHtml(m.from||'')}" placeholder="sna@example.com" required></label>
<label>Korisničko ime <input id="mUser" value="${escapeHtml(m.username||'')}"></label>
<label>Lozinka <input id="mPass" type="password" placeholder="${m.hasPassword?'•••••• (nepromijenjeno)':''}"></label>
<label>Primatelji (zarezom) <input id="mRcpt" value="${escapeHtml((m.recipients||[]).join(', '))}" required></label>
<label>Minimalna razina za alarm <select id="mSev">${sev.map(s=>`<option ${s===m.minSeverity?'selected':''}>${s}</option>`).join('')}</select></label>
<label><input id="mEnabled" type="checkbox" ${m.enabled?'checked':''}> Alarmi uključeni</label>
<div><button type="submit">Spremi</button> <button type="button" id="mailTest">Test mail</button></div>
<p class="muted">Prvi događaj šalje se odmah; duplikati se agregiraju 10 minuta pa stiže sažetak. Preporuka: prije uključivanja alarma pošaljite test.</p>
<div id="mailMsg" class="muted"></div></form></div>`;
const payload=()=>({enabled:$('#mEnabled').checked,host:$('#mHost').value.trim(),port:parseInt($('#mPort').value,10),tlsMode:$('#mTls').value,from:$('#mFrom').value.trim(),username:$('#mUser').value.trim(),password:$('#mPass').value,recipients:$('#mRcpt').value.split(',').map(s=>s.trim()).filter(Boolean),minSeverity:$('#mSev').value});
$('#mailForm').onsubmit=async e=>{e.preventDefault();$('#mailMsg').textContent='';try{await api('/api/mail',{method:'PUT',body:JSON.stringify(payload())});$('#mailMsg').textContent='Spremljeno.';$('#mPass').value=''}catch(err){$('#mailMsg').textContent=err.message}};
$('#mailTest').onclick=async()=>{$('#mailMsg').textContent='Slanje testa…';try{await api('/api/mail',{method:'PUT',body:JSON.stringify(payload())});await api('/api/mail/test',{method:'POST',body:'{}'});$('#mailMsg').textContent='Test mail poslan — provjerite sandučić.'}catch(err){$('#mailMsg').textContent=err.message}}}
async function audit(){const rows=await api('/api/audit');$('#content').innerHTML=`<div class="panel"><table><thead><tr><th>Vrijeme</th><th>Razina</th><th>Korisnik</th><th>Akcija</th><th>Cilj</th><th>Rezultat</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.time).toLocaleString()}</td><td>${escapeHtml(x.severity||'info')}</td><td>${escapeHtml(x.actor)}</td><td>${escapeHtml(x.action)}</td><td>${escapeHtml(x.target)}</td><td>${escapeHtml(x.result)}</td></tr>`).join('')}</tbody></table></div>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';showShell()}catch(err){$('#loginError').textContent=err.message}}
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}finally{showLogin()}}
api('/api/dashboard').then(showShell).catch(showLogin);
