const modules=[['dashboard','Dashboard','Pregled mrežne infrastrukture'],['dns','DNS','PowerDNS zone i zapisi'],['dhcp','DHCP','Kea subneti, rezervacije i leaseovi'],['certificates','Certificates','Step CA i javni ACME certifikati'],['proxy','Reverse Proxy','Nginx aplikacije i TLS'],['monitoring','Monitoring','Zdravlje servisa i upozorenja'],['backup','Backup','Sigurne kopije i povrat podataka'],['mail','Mail','SMTP alarmi i agregacija događaja'],['users','Users','Korisnici, MFA i ovlasti'],['audit','Audit log','Evidencija administratorskih promjena']];
const $=s=>document.querySelector(s); let current='dashboard';
function csrfToken(){const m=document.cookie.match(/(?:^|;\s*)saguaro_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):''}
async function api(path,options={}){const headers={'Content-Type':'application/json'};const method=(options.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){headers['X-CSRF-Token']=csrfToken()}const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});if(r.status===401){showLogin();throw Error('Prijava je istekla.')}const body=await r.json();if(!r.ok)throw Error(body.error||'Greška zahtjeva');return body}
function showLogin(){$('#login').classList.remove('hidden');$('#shell').classList.add('hidden')}
function showShell(){$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');renderNav();openModule(current)}
function renderNav(){const nav=$('#nav');nav.innerHTML='';for(const [id,name] of modules){const b=document.createElement('button');b.textContent=name;b.className=id===current?'active':'';b.onclick=()=>openModule(id);nav.appendChild(b)}}
async function openModule(id){current=id;renderNav();const m=modules.find(x=>x[0]===id);$('#title').textContent=m[1];$('#description').textContent=m[2];$('#content').innerHTML='<div class="panel muted">Učitavanje…</div>';try{id==='dashboard'?await dashboard():id==='audit'?await audit():id==='monitoring'?await monitoring():id==='mail'?await mailPage():id==='dns'?await dnsPage():id==='dhcp'?await dhcpPage():id==='users'?await usersPage():await modulePage(id)}catch(e){$('#content').innerHTML=`<div class="panel error">${escapeHtml(e.message)}</div>`}}
async function dashboard(){const [d,services]=await Promise.all([api('/api/dashboard'),api('/api/services')]);$('#content').innerHTML=`<div class="cards"><div class="card"><div class="muted">Servisi</div><div class="metric">${d.services}</div></div><div class="card"><div class="muted">Konfigurirano</div><div class="metric">${d.configured}</div></div><div class="card"><div class="muted">Zdravo</div><div class="metric">${d.healthy}</div></div><div class="card"><div class="muted">Upozorenja</div><div class="metric">${d.alerts}</div></div></div><div class="panel"><h2>Čarobnjaci</h2><p class="muted">Vođeno dodavanje uz validaciju i pregled prije primjene.</p><div class="wizRow"><button id="wzNet">DHCP mreža (W2)</button> <button id="wzRes">DHCP rezervacija (W3)</button> <button id="wzZone">DNS zona (W4)</button> <button id="wzMail">Mail alarmi (W10)</button></div></div><div class="panel"><h2>Komponente</h2><div class="services">${services.map(s=>`<div class="card service"><div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p></div><div><div class="status">${escapeHtml(s.status)}</div><button onclick="checkService('${s.id}')">Provjeri</button></div></div>`).join('')}</div></div>`;$('#wzNet').onclick=wizDhcpNet;$('#wzRes').onclick=wizReservation;$('#wzZone').onclick=wizDnsZone;$('#wzMail').onclick=()=>openModule('mail')}
async function checkService(id){try{const r=await api(`/api/services/${id}/actions/check`,{method:'POST',body:'{}'});alert(`${r.result.id}: ${r.result.status}\n${r.result.detail||''} (${r.result.latencyMs} ms)`);openModule(current)}catch(e){alert(e.message)}}
async function modulePage(id){const details={dns:['Zone i zapisi','U idućem milestoneu: forward/reverse zone, DNSSEC, ACL i validirani reload.'],dhcp:['Kea DHCP','Subneti, poolovi, rezervacije, KNOWN/UNKNOWN/DROP klase i quarantine politike.'],certificates:['Upravljanje certifikatima','Step CA za internu PKI te ACME/Let’s Encrypt za javne domene.'],proxy:['Nginx aplikacije','Deklarativni virtual hosts, TLS, WebSocket i rollback nakon nginx -t provjere.'],monitoring:['Monitoring','Servisi, resursi, DHCP poolovi, DNS greške i certifikati pred istekom.'],backup:['Backup','Šifrirane kopije, retention, provjera integriteta i restore test.'],users:['Korisnici i uloge','Planirane uloge: admin, network-operator, dns-operator, auditor i read-only.']}[id];$('#content').innerHTML=`<div class="panel"><h2>${details[0]}</h2><p class="muted">${details[1]}</p><p>Modul je registriran u GUI-ju; CRUD adapter dolazi u sljedećem koraku.</p></div>`}
async function monitoring(){const rows=await api('/api/events?limit=100');$('#content').innerHTML=`<div class="panel"><h2>Događaji (zadnjih ${rows.length})</h2><table><thead><tr><th>Vrijeme</th><th>Razina</th><th>Modul</th><th>Akcija</th><th>Poruka</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td>${escapeHtml(x.severity)}</td><td>${escapeHtml(x.module)}</td><td>${escapeHtml(x.action||'')}</td><td>${escapeHtml(x.message)}</td></tr>`).join('')}</tbody></table></div>`}
const ROLES=['admin','network-operator','dns-operator','auditor','read-only'];
async function usersPage(){const me=await api('/api/profile');let list=null;try{list=await api('/api/users')}catch(e){list=null}
const mine=`<div class="panel"><h2>Moj račun</h2><p>Korisnik: <b>${escapeHtml(me.username)}</b> — uloga: <b>${escapeHtml(me.role)}</b></p>
<form id="pwForm" class="stack"><h3>Promjena lozinke</h3><label>Trenutna lozinka <input id="pwOld" type="password" required></label><label>Nova lozinka (min. 14 znakova) <input id="pwNew" type="password" minlength="14" required></label><div><button type="submit">Promijeni</button></div><div id="pwMsg" class="muted"></div></form></div>`;
const admin=list===null?'':`<div class="panel"><h2>Korisnici (${list.length})</h2><table><thead><tr><th>Korisnik</th><th>Uloga</th><th>Aktivan</th><th></th></tr></thead><tbody>${list.map(u=>`<tr><td>${escapeHtml(u.username)}</td><td><select class="uRole" data-u="${escapeHtml(u.username)}">${ROLES.map(r=>`<option ${r===u.role?'selected':''}>${r}</option>`).join('')}</select></td><td>${u.enabled?'da':'ne'}</td><td><button class="uToggle" data-u="${escapeHtml(u.username)}" data-e="${u.enabled?1:0}">${u.enabled?'Onemogući':'Omogući'}</button> <button class="uReset" data-u="${escapeHtml(u.username)}">Reset lozinke</button> <button class="uDel" data-u="${escapeHtml(u.username)}">Obriši</button></td></tr>`).join('')}</tbody></table>
<form id="uAdd" class="stack"><h3>Novi korisnik</h3><label>Korisničko ime <input id="uName" required></label><label>Lozinka (min. 14) <input id="uPass" type="password" minlength="14" required></label><label>Uloga <select id="uNewRole">${ROLES.map(r=>`<option>${r}</option>`).join('')}</select></label><div><button type="submit">Dodaj</button></div><div id="uMsg" class="muted"></div></form></div>`;
$('#content').innerHTML=mine+admin;
$('#pwForm').onsubmit=async e=>{e.preventDefault();$('#pwMsg').textContent='';try{await api('/api/profile/password',{method:'POST',body:JSON.stringify({oldPassword:$('#pwOld').value,newPassword:$('#pwNew').value})});$('#pwMsg').textContent='Lozinka promijenjena.';$('#pwOld').value='';$('#pwNew').value=''}catch(err){$('#pwMsg').textContent=err.message}};
if(list===null)return;
const patch=async(u,body)=>{try{await api(`/api/users/${encodeURIComponent(u)}`,{method:'PATCH',body:JSON.stringify(body)});usersPage()}catch(err){alert(err.message)}};
document.querySelectorAll('.uRole').forEach(el=>el.onchange=()=>patch(el.dataset.u,{role:el.value}));
document.querySelectorAll('.uToggle').forEach(el=>el.onclick=()=>patch(el.dataset.u,{enabled:el.dataset.e!=='1'}));
document.querySelectorAll('.uReset').forEach(el=>el.onclick=()=>{const p=prompt(`Nova lozinka za ${el.dataset.u} (min. 14 znakova):`);if(p)patch(el.dataset.u,{password:p})});
document.querySelectorAll('.uDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati korisnika ${el.dataset.u}?`))return;try{await api(`/api/users/${encodeURIComponent(el.dataset.u)}`,{method:'DELETE'});usersPage()}catch(err){alert(err.message)}});
$('#uAdd').onsubmit=async e=>{e.preventDefault();$('#uMsg').textContent='';try{await api('/api/users',{method:'POST',body:JSON.stringify({username:$('#uName').value.trim(),password:$('#uPass').value,role:$('#uNewRole').value})});usersPage()}catch(err){$('#uMsg').textContent=err.message}}}
let dnsZone=null;
async function dnsPage(){const zones=await api('/api/dns/zones');
$('#content').innerHTML=`<div class="panel"><h2>Zone (${zones.length})</h2><table><thead><tr><th>Zona</th><th>Vrsta</th><th>Serial</th><th></th></tr></thead><tbody>${zones.map(z=>`<tr><td><a href="#" class="zoneLink" data-z="${escapeHtml(z.name)}">${escapeHtml(z.name)}</a></td><td>${escapeHtml(z.kind)}</td><td>${z.serial||''}</td><td><button class="zoneDel" data-z="${escapeHtml(z.name)}">Obriši</button></td></tr>`).join('')}</tbody></table>
<form id="zoneAdd" class="stack"><h3>Nova zona</h3><label>Naziv <input id="zName" placeholder="example.internal" required></label><label>Nameserveri (zarezom) <input id="zNs" placeholder="ns1.example.internal" required></label><div><button type="submit">Dodaj zonu</button></div><div id="zMsg" class="muted"></div></form></div><div id="zoneDetail"></div>`;
document.querySelectorAll('.zoneLink').forEach(el=>el.onclick=e=>{e.preventDefault();openZone(el.dataset.z).catch(err=>alert(err.message))});
document.querySelectorAll('.zoneDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati zonu ${el.dataset.z}? Zapisi se brišu iz PowerDNS-a.`))return;try{await api(`/api/dns/zones/${encodeURIComponent(el.dataset.z)}`,{method:'DELETE'});dnsZone=null;dnsPage()}catch(err){alert(err.message)}});
$('#zoneAdd').onsubmit=async e=>{e.preventDefault();$('#zMsg').textContent='';try{await api('/api/dns/zones',{method:'POST',body:JSON.stringify({name:$('#zName').value.trim(),nameservers:$('#zNs').value.split(',').map(s=>s.trim()).filter(Boolean)})});dnsPage()}catch(err){$('#zMsg').textContent=err.message}};
if(dnsZone)await openZone(dnsZone)}
async function openZone(name){dnsZone=name;const d=await api(`/api/dns/zones/${encodeURIComponent(name)}`);const hidden=['SOA','RRSIG','NSEC','NSEC3','NSEC3PARAM','DNSKEY','CDS','CDNSKEY'];const sets=(d.rrsets||[]).filter(s=>!hidden.includes(s.type));
$('#zoneDetail').innerHTML=`<div class="panel"><h2>Zapisi — ${escapeHtml(name)}</h2><table><thead><tr><th>Ime</th><th>Tip</th><th>TTL</th><th>Vrijednosti</th><th></th></tr></thead><tbody>${sets.map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.type)}</td><td>${s.ttl}</td><td>${escapeHtml((s.records||[]).map(r=>r.content).join(', '))}</td><td><button class="recDel" data-n="${escapeHtml(s.name)}" data-t="${escapeHtml(s.type)}">Obriši</button></td></tr>`).join('')}</tbody></table>
<form id="recAdd" class="stack"><h3>Dodaj / uredi zapis</h3><label>Ime (FQDN) <input id="rName" placeholder="host.${escapeHtml(name)}" required></label><label>Tip <select id="rType">${['A','AAAA','CNAME','TXT','MX','SRV','NS','PTR','CAA'].map(t=>`<option>${t}</option>`).join('')}</select></label><label>TTL <input id="rTtl" type="number" value="3600" min="1"></label><label>Vrijednosti (zarezom) <input id="rVal" placeholder="192.168.10.20" required></label><div><button type="submit">Spremi zapis</button></div><div id="rMsg" class="muted"></div></form></div>`;
document.querySelectorAll('.recDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati ${el.dataset.n} ${el.dataset.t}?`))return;try{await api(`/api/dns/zones/${encodeURIComponent(name)}/records`,{method:'PUT',body:JSON.stringify({name:el.dataset.n,type:el.dataset.t,delete:true,ttl:0,contents:[]})});openZone(name)}catch(err){alert(err.message)}});
$('#recAdd').onsubmit=async e=>{e.preventDefault();$('#rMsg').textContent='';try{await api(`/api/dns/zones/${encodeURIComponent(name)}/records`,{method:'PUT',body:JSON.stringify({name:$('#rName').value.trim(),type:$('#rType').value,ttl:parseInt($('#rTtl').value,10)||3600,contents:$('#rVal').value.split(',').map(s=>s.trim()).filter(Boolean),delete:false})});openZone(name)}catch(err){$('#rMsg').textContent=err.message}}}
async function dhcpPage(){const get=p=>api(p).catch(e=>({err:e.message}));const [subnets,leases,resv]=await Promise.all([get('/api/dhcp/subnets'),get('/api/dhcp/leases'),get('/api/dhcp/reservations')]);
const sub=subnets.err?`<p class="muted">${escapeHtml(subnets.err)}</p>`:`<table><thead><tr><th>ID</th><th>Subnet</th><th>Poolovi</th><th></th></tr></thead><tbody>${subnets.map(s=>`<tr><td>${s.id}</td><td>${escapeHtml(s.subnet)}</td><td>${escapeHtml((s.pools||[]).join(', '))}</td><td><button class="subEdit" data-id="${s.id}" data-subnet="${escapeHtml(s.subnet)}" data-pool="${escapeHtml((s.pools||[])[0]||'')}">Uredi</button> <button class="subDel" data-id="${s.id}">Obriši</button></td></tr>`).join('')}</tbody></table>`;
const subForm=`<form id="subForm" class="stack"><h3 id="subFormTitle">Novi subnet</h3><input type="hidden" id="subId" value="">
<label>Subnet (CIDR) <input id="subCidr" placeholder="192.168.20.0/24" required></label>
<label>Pool od <input id="subPoolStart" placeholder="192.168.20.100" required></label>
<label>Pool do <input id="subPoolEnd" placeholder="192.168.20.200" required></label>
<label>Router (gateway) <input id="subRouter" placeholder="192.168.20.1"></label>
<label>DNS serveri (zarezom) <input id="subDns" placeholder="192.168.20.1"></label>
<label>Domena <input id="subDomain" placeholder="example.internal"></label>
<div><button type="submit">Spremi subnet</button> <button type="button" id="subReset">Poništi</button></div>
<p class="muted">Promjena ide kroz transakciju: config-test → config-set → provjera → config-write (uz automatski rollback na grešku).</p>
<div id="subMsg" class="muted"></div></form>`;
const lea=leases.err?`<p class="muted">${escapeHtml(leases.err)}</p>`:`<table><thead><tr><th>IP</th><th>MAC</th><th>Hostname</th><th>Subnet</th><th>Istječe</th></tr></thead><tbody>${leases.map(l=>`<tr><td>${escapeHtml(l.ip)}</td><td>${escapeHtml(l.mac)}</td><td>${escapeHtml(l.hostname||'')}</td><td>${l.subnetId}</td><td>${l.expires?new Date(l.expires*1000).toLocaleString():''}</td></tr>`).join('')}</tbody></table>`;
const res=resv.err?`<p class="muted">${escapeHtml(resv.err)}</p>`:`<table><thead><tr><th>IP</th><th>MAC</th><th>Hostname</th><th>Subnet</th><th></th></tr></thead><tbody>${resv.map(x=>`<tr><td>${escapeHtml(x.ip)}</td><td>${escapeHtml(x.mac)}</td><td>${escapeHtml(x.hostname||'')}</td><td>${x.subnetId}</td><td><button class="resDel" data-id="${x.id}">Obriši</button></td></tr>`).join('')}</tbody></table>`;
const subOpts=subnets.err?'<option value="1">1</option>':subnets.map(s=>`<option value="${s.id}">${s.id} — ${escapeHtml(s.subnet)}</option>`).join('');
$('#content').innerHTML=`<div class="panel"><h2>Subneti</h2>${sub}${subForm}</div><div class="panel"><h2>Aktivni leaseovi (${leases.err?'—':leases.length})</h2>${lea}</div><div class="panel"><h2>Rezervacije</h2>${res}
<form id="resAdd" class="stack"><h3>Nova rezervacija</h3><label>MAC <input id="resMac" placeholder="aa:bb:cc:dd:ee:ff" required></label><label>IP <input id="resIp" placeholder="192.168.10.50" required></label><label>Hostname <input id="resHost"></label><label>Subnet <select id="resSub">${subOpts}</select></label><div><button type="submit">Dodaj rezervaciju</button></div><div id="resMsg" class="muted"></div></form></div>`;
const subPayload=()=>({subnet:$('#subCidr').value.trim(),poolStart:$('#subPoolStart').value.trim(),poolEnd:$('#subPoolEnd').value.trim(),router:$('#subRouter').value.trim(),domain:$('#subDomain').value.trim(),dnsServers:$('#subDns').value.split(',').map(s=>s.trim()).filter(Boolean)});
$('#subForm').onsubmit=async e=>{e.preventDefault();$('#subMsg').textContent='Primjena…';const id=$('#subId').value;try{if(id){await api(`/api/dhcp/subnets/${id}`,{method:'PUT',body:JSON.stringify(subPayload())})}else{await api('/api/dhcp/subnets',{method:'POST',body:JSON.stringify(subPayload())})}dhcpPage()}catch(err){$('#subMsg').textContent=err.message}};
$('#subReset').onclick=()=>{$('#subId').value='';$('#subFormTitle').textContent='Novi subnet';['subCidr','subPoolStart','subPoolEnd','subRouter','subDns','subDomain'].forEach(i=>$('#'+i).value='');$('#subCidr').disabled=false};
document.querySelectorAll('.subEdit').forEach(el=>el.onclick=()=>{$('#subId').value=el.dataset.id;$('#subFormTitle').textContent=`Uredi subnet ${el.dataset.subnet} (ID ${el.dataset.id})`;$('#subCidr').value=el.dataset.subnet;$('#subCidr').disabled=true;const p=(el.dataset.pool||'').split('-').map(s=>s.trim());$('#subPoolStart').value=p[0]||'';$('#subPoolEnd').value=p[1]||'';$('#subMsg').textContent='CIDR se ne mijenja — za promjenu CIDR-a obrišite pa dodajte subnet.'});
document.querySelectorAll('.subDel').forEach(el=>el.onclick=async()=>{if(!confirm(`Obrisati subnet ID ${el.dataset.id}? DHCP za taj segment prestaje raditi.`))return;try{await api(`/api/dhcp/subnets/${el.dataset.id}`,{method:'DELETE'});dhcpPage()}catch(err){if(err.message.includes('force=true')&&confirm(err.message+'\n\nObrisati zajedno s rezervacijama?')){try{await api(`/api/dhcp/subnets/${el.dataset.id}?force=true`,{method:'DELETE'});dhcpPage()}catch(e2){alert(e2.message)}}else{alert(err.message)}}});
document.querySelectorAll('.resDel').forEach(el=>el.onclick=async()=>{if(!confirm('Obrisati rezervaciju?'))return;try{await api(`/api/dhcp/reservations/${el.dataset.id}`,{method:'DELETE'});dhcpPage()}catch(err){alert(err.message)}});
$('#resAdd').onsubmit=async e=>{e.preventDefault();$('#resMsg').textContent='';try{await api('/api/dhcp/reservations',{method:'POST',body:JSON.stringify({mac:$('#resMac').value.trim(),ip:$('#resIp').value.trim(),hostname:$('#resHost').value.trim(),subnetId:parseInt($('#resSub').value,10),id:0})});$('#resMsg').textContent='Rezervacija dodana — aktivna je za nove DHCP zahtjeve.';dhcpPage()}catch(err){$('#resMsg').textContent=err.message}}}
async function mailPage(){const m=await api('/api/mail');const sev=['info','notice','warning','error','critical','security'];$('#content').innerHTML=`<div class="panel"><h2>SMTP postavke</h2><form id="mailForm" class="stack">
<label>Server <input id="mHost" value="${escapeHtml(m.host||'')}" placeholder="smtp.smtp2go.com" required></label>
<label>Port <input id="mPort" type="number" value="${m.port||587}" min="1" max="65535" required></label>
<label>TLS <select id="mTls">${['starttls','tls','none'].map(t=>`<option ${t===m.tlsMode?'selected':''}>${t}</option>`).join('')}</select></label>
<label>From <input id="mFrom" type="email" value="${escapeHtml(m.from||'')}" placeholder="sna@example.com" required></label>
<label>Korisničko ime <input id="mUser" value="${escapeHtml(m.username||'')}"></label>
<label>Lozinka <input id="mPass" type="password" placeholder="${m.hasPassword?'•••••• (nepromijenjeno)':''}"></label>
<label>Primatelji (zarezom) <input id="mRcpt" value="${escapeHtml((m.recipients||[]).join(', '))}" required></label>
<label>Minimalna razina za alarm <select id="mSev">${sev.map(s=>`<option ${s===m.minSeverity?'selected':''}>${s}</option>`).join('')}</select></label>
<label><input id="mEnabled" type="checkbox" ${m.enabled?'checked':''}> Alarmi uključeni</label>
<div><button type="submit">Spremi</button> <button type="button" id="mailTest">Test mail</button></div>
<p class="muted">Prvi događaj šalje se odmah; duplikati se agregiraju 10 minuta pa stiže sažetak. Preporuka: prije uključivanja alarma pošaljite test.</p>
<div id="mailMsg" class="muted"></div></form></div>`;
const payload=()=>({enabled:$('#mEnabled').checked,host:$('#mHost').value.trim(),port:parseInt($('#mPort').value,10),tlsMode:$('#mTls').value,from:$('#mFrom').value.trim(),username:$('#mUser').value.trim(),password:$('#mPass').value,recipients:$('#mRcpt').value.split(',').map(s=>s.trim()).filter(Boolean),minSeverity:$('#mSev').value});
$('#mailForm').onsubmit=async e=>{e.preventDefault();$('#mailMsg').textContent='';try{await api('/api/mail',{method:'PUT',body:JSON.stringify(payload())});$('#mailMsg').textContent='Spremljeno.';$('#mPass').value=''}catch(err){$('#mailMsg').textContent=err.message}};
$('#mailTest').onclick=async()=>{$('#mailMsg').textContent='Slanje testa…';try{await api('/api/mail',{method:'PUT',body:JSON.stringify(payload())});await api('/api/mail/test',{method:'POST',body:'{}'});$('#mailMsg').textContent='Test mail poslan — provjerite sandučić.'}catch(err){$('#mailMsg').textContent=err.message}}}
async function audit(){const rows=await api('/api/audit');$('#content').innerHTML=`<div class="panel"><table><thead><tr><th>Vrijeme</th><th>Razina</th><th>Korisnik</th><th>Akcija</th><th>Cilj</th><th>Rezultat</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.time).toLocaleString()}</td><td>${escapeHtml(x.severity||'info')}</td><td>${escapeHtml(x.actor)}</td><td>${escapeHtml(x.action)}</td><td>${escapeHtml(x.target)}</td><td>${escapeHtml(x.result)}</td></tr>`).join('')}</tbody></table></div>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const res=await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';res.mustChangePassword?showForcedChange():showShell()}catch(err){$('#loginError').textContent=err.message}}
function showForcedChange(){const ov=document.createElement('div');ov.className='overlay';ov.innerHTML=`<div class="modal"><h2>Obavezna promjena lozinke</h2><p class="muted">Prva prijava (ili reset lozinke): postavite vlastitu lozinku prije nastavka. Ostale funkcije su do tada blokirane.</p><form id="fcForm" class="stack"><label>Trenutna (bootstrap) lozinka <input id="fcOld" type="password" required></label><label>Nova lozinka (min. 14 znakova) <input id="fcNew" type="password" minlength="14" required></label><label>Ponovi novu lozinku <input id="fcNew2" type="password" minlength="14" required></label><div><button type="submit">Postavi lozinku</button></div><div id="fcMsg" class="error"></div></form></div>`;document.body.appendChild(ov);
$('#fcForm').onsubmit=async e=>{e.preventDefault();if($('#fcNew').value!==$('#fcNew2').value){$('#fcMsg').textContent='Lozinke se ne podudaraju.';return}try{await api('/api/profile/password',{method:'POST',body:JSON.stringify({oldPassword:$('#fcOld').value,newPassword:$('#fcNew').value})});ov.remove();showShell()}catch(err){$('#fcMsg').textContent=err.message}}}
function runWizard(title,steps,onFinish){let idx=0;const state={};const ov=document.createElement('div');ov.className='overlay';document.body.appendChild(ov);const close=()=>ov.remove();
const draw=()=>{ov.innerHTML=`<div class="modal"><h2>${escapeHtml(title)}</h2><p class="muted">Korak ${idx+1}/${steps.length}: ${escapeHtml(steps[idx].title)}</p><div id="wizBody" class="stack">${steps[idx].render(state)}</div><div class="wizNav"><button type="button" id="wizCancel" class="ghost">Odustani</button>${idx>0?'<button type="button" id="wizBack" class="ghost">Natrag</button>':''}<button type="button" id="wizNext">${idx===steps.length-1?'Primijeni':'Dalje'}</button></div><div id="wizMsg" class="muted"></div></div>`;
$('#wizCancel').onclick=close;if(idx>0)$('#wizBack').onclick=()=>{idx--;draw()};
$('#wizNext').onclick=async()=>{const err=steps[idx].collect?steps[idx].collect(state):null;if(err){$('#wizMsg').textContent=err;return}if(idx<steps.length-1){idx++;draw()}else{$('#wizMsg').textContent='Primjena…';try{await onFinish(state);close()}catch(e){$('#wizMsg').textContent=e.message}}}};draw()}
function wizDhcpNet(){runWizard('Čarobnjak: DHCP mreža (W2)',[
{title:'Mreža',render:s=>`<label>Subnet (CIDR) <input id="w1cidr" value="${escapeHtml(s.subnet||'')}" placeholder="192.168.20.0/24"></label><label>Gateway (router) <input id="w1gw" value="${escapeHtml(s.router||'')}" placeholder="192.168.20.1"></label>`,collect:s=>{s.subnet=$('#w1cidr').value.trim();s.router=$('#w1gw').value.trim();return s.subnet?null:'Unesite subnet.'}},
{title:'Pool i opcije',render:s=>`<label>Pool od <input id="w2ps" value="${escapeHtml(s.poolStart||'')}" placeholder="192.168.20.100"></label><label>Pool do <input id="w2pe" value="${escapeHtml(s.poolEnd||'')}" placeholder="192.168.20.200"></label><label>DNS serveri (zarezom) <input id="w2dns" value="${escapeHtml(s.dns||s.router||'')}"></label><label>Domena <input id="w2dom" value="${escapeHtml(s.domain||'')}"></label>`,collect:s=>{s.poolStart=$('#w2ps').value.trim();s.poolEnd=$('#w2pe').value.trim();s.dns=$('#w2dns').value.trim();s.domain=$('#w2dom').value.trim();return(s.poolStart&&s.poolEnd)?null:'Unesite pool.'}},
{title:'Pregled',render:s=>`<p>Subnet: <b>${escapeHtml(s.subnet)}</b><br>Pool: <b>${escapeHtml(s.poolStart)} – ${escapeHtml(s.poolEnd)}</b><br>Gateway: <b>${escapeHtml(s.router||'—')}</b><br>DNS: <b>${escapeHtml(s.dns||'—')}</b><br>Domena: <b>${escapeHtml(s.domain||'—')}</b></p><p class="muted">Primjena ide kroz Kea transakciju s validacijom i automatskim rollbackom. Server odbija subnet koji se preklapa s postojećim.</p>`}],
async s=>{await api('/api/dhcp/subnets',{method:'POST',body:JSON.stringify({subnet:s.subnet,poolStart:s.poolStart,poolEnd:s.poolEnd,router:s.router,domain:s.domain,dnsServers:s.dns?s.dns.split(',').map(x=>x.trim()).filter(Boolean):[]})});openModule('dhcp')})}
async function wizReservation(){let leases=[];let subnets=[];try{leases=await api('/api/dhcp/leases')}catch(e){}try{subnets=await api('/api/dhcp/subnets')}catch(e){}
runWizard('Čarobnjak: DHCP rezervacija (W3)',[
{title:'Odabir uređaja',render:s=>`<label>Uređaj iz aktivnih leaseova <select id="w1lease"><option value="">— ručni unos —</option>${leases.map((l,i)=>`<option value="${i}" ${s.leaseIdx===String(i)?'selected':''}>${escapeHtml(l.ip)} · ${escapeHtml(l.mac)} · ${escapeHtml(l.hostname||'')}</option>`).join('')}</select></label>`,collect:s=>{s.leaseIdx=$('#w1lease').value;if(s.leaseIdx!==''){const l=leases[parseInt(s.leaseIdx,10)];s.mac=l.mac;s.ip=l.ip;s.hostname=l.hostname||'';s.subnetId=l.subnetId}return null}},
{title:'Podaci rezervacije',render:s=>`<label>MAC <input id="w2mac" value="${escapeHtml(s.mac||'')}" placeholder="aa:bb:cc:dd:ee:ff"></label><label>IP <input id="w2ip" value="${escapeHtml(s.ip||'')}"></label><label>Hostname <input id="w2host" value="${escapeHtml(s.hostname||'')}"></label><label>Subnet <select id="w2sub">${subnets.map(x=>`<option value="${x.id}" ${x.id===s.subnetId?'selected':''}>${x.id} — ${escapeHtml(x.subnet)}</option>`).join('')||'<option value="1">1</option>'}</select></label>`,collect:s=>{s.mac=$('#w2mac').value.trim();s.ip=$('#w2ip').value.trim();s.hostname=$('#w2host').value.trim();s.subnetId=parseInt($('#w2sub').value,10);return(s.mac&&s.ip)?null:'Unesite MAC i IP.'}},
{title:'Pregled',render:s=>{const sub=subnets.find(x=>x.id===s.subnetId);const pool=sub&&(sub.pools||[])[0]||'';let warn='';if(pool){const[ps,pe]=pool.split('-').map(x=>x.trim());const n=ip=>ip.split('.').reduce((a,o)=>a*256+ +o,0);try{if(n(s.ip)>=n(ps)&&n(s.ip)<=n(pe))warn='<p class="error">Upozorenje: IP je unutar dinamičkog poola — preporuka je rezervirati adresu izvan poola.</p>'}catch(e){}}
return`<p>MAC: <b>${escapeHtml(s.mac)}</b><br>IP: <b>${escapeHtml(s.ip)}</b><br>Hostname: <b>${escapeHtml(s.hostname||'—')}</b><br>Subnet ID: <b>${s.subnetId}</b></p>${warn}<p class="muted">Server odbija duplikat MAC-a u subnetu i duplikat IP-a. Rezervacija vrijedi odmah za nove DHCP zahtjeve.</p>`}}],
async s=>{await api('/api/dhcp/reservations',{method:'POST',body:JSON.stringify({id:0,mac:s.mac,ip:s.ip,hostname:s.hostname,subnetId:s.subnetId})});openModule('dhcp')})}
function wizDnsZone(){runWizard('Čarobnjak: DNS zona (W4)',[
{title:'Tip zone',render:s=>`<label>Tip <select id="w1type"><option value="forward" ${s.type!=='reverse'?'selected':''}>Forward</option><option value="reverse" ${s.type==='reverse'?'selected':''}>Reverse (PTR)</option></select></label><label>Za reverse: subnet (CIDR /24) <input id="w1sub" value="${escapeHtml(s.revSubnet||'')}" placeholder="192.168.20.0/24"></label>`,collect:s=>{s.type=$('#w1type').value;s.revSubnet=$('#w1sub').value.trim();if(s.type==='reverse'){const m=s.revSubnet.match(/^(\d+)\.(\d+)\.(\d+)\.\d+\/24$/);if(!m)return'Reverse zona u ovoj verziji traži /24 subnet.';s.name=`${m[3]}.${m[2]}.${m[1]}.in-addr.arpa`}return null}},
{title:'Ime i nameserveri',render:s=>`<label>Ime zone <input id="w2name" value="${escapeHtml(s.name||'')}" placeholder="example.internal" ${s.type==='reverse'?'readonly':''}></label><label>Nameserveri (zarezom) <input id="w2ns" value="${escapeHtml(s.ns||('ns1.'+(s.type==='reverse'?'':(s.name||''))))}" placeholder="ns1.example.internal"></label>`,collect:s=>{s.name=$('#w2name').value.trim();s.ns=$('#w2ns').value.trim();return(s.name&&s.ns)?null:'Unesite ime zone i barem jedan nameserver.'}},
{title:'Pregled',render:s=>`<p>Zona: <b>${escapeHtml(s.name)}</b> (${escapeHtml(s.type)})<br>Nameserveri: <b>${escapeHtml(s.ns)}</b></p><p class="muted">PowerDNS automatski kreira SOA i NS zapise. Kolizija s postojećom zonom bit će odbijena.</p>`}],
async s=>{await api('/api/dns/zones',{method:'POST',body:JSON.stringify({name:s.name,nameservers:s.ns.split(',').map(x=>x.trim()).filter(Boolean)})});openModule('dns')})}
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}finally{showLogin()}}
api('/api/dashboard').then(showShell).catch(showLogin);
