const modules=[['dashboard','Dashboard','Pregled mrežne infrastrukture'],['dns','DNS','BIND9 zone i zapisi'],['dhcp','DHCP','Kea subneti, rezervacije i leaseovi'],['certificates','Certificates','Step CA i javni ACME certifikati'],['proxy','Reverse Proxy','Nginx aplikacije i TLS'],['monitoring','Monitoring','Zdravlje servisa i upozorenja'],['backup','Backup','Sigurne kopije i povrat podataka'],['mail','Mail','SMTP alarmi i agregacija događaja'],['users','Users','Korisnici, MFA i ovlasti'],['audit','Audit log','Evidencija administratorskih promjena']];
const $=s=>document.querySelector(s); let current='dashboard';
function csrfToken(){const m=document.cookie.match(/(?:^|;\s*)saguaro_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):''}
async function api(path,options={}){const headers={'Content-Type':'application/json'};const method=(options.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){headers['X-CSRF-Token']=csrfToken()}const r=await fetch(path,{...options,headers:{...headers,...(options.headers||{})}});if(r.status===401){showLogin();throw Error('Prijava je istekla.')}const body=await r.json();if(!r.ok)throw Error(body.error||'Greška zahtjeva');return body}
function showLogin(){$('#login').classList.remove('hidden');$('#shell').classList.add('hidden')}
function showShell(){$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');renderNav();openModule(current)}
function renderNav(){const nav=$('#nav');nav.innerHTML='';for(const [id,name] of modules){const b=document.createElement('button');b.textContent=name;b.className=id===current?'active':'';b.onclick=()=>openModule(id);nav.appendChild(b)}}
async function openModule(id){current=id;renderNav();const m=modules.find(x=>x[0]===id);$('#title').textContent=m[1];$('#description').textContent=m[2];$('#content').innerHTML='<div class="panel muted">Učitavanje…</div>';try{id==='dashboard'?await dashboard():id==='audit'?await audit():id==='monitoring'?await monitoring():id==='mail'?await mailPage():await modulePage(id)}catch(e){$('#content').innerHTML=`<div class="panel error">${escapeHtml(e.message)}</div>`}}
async function dashboard(){const [d,services]=await Promise.all([api('/api/dashboard'),api('/api/services')]);$('#content').innerHTML=`<div class="cards"><div class="card"><div class="muted">Servisi</div><div class="metric">${d.services}</div></div><div class="card"><div class="muted">Konfigurirano</div><div class="metric">${d.configured}</div></div><div class="card"><div class="muted">Zdravo</div><div class="metric">${d.healthy}</div></div><div class="card"><div class="muted">Upozorenja</div><div class="metric">${d.alerts}</div></div></div><div class="panel"><h2>Komponente</h2><div class="services">${services.map(s=>`<div class="card service"><div><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p></div><div><div class="status">${escapeHtml(s.status)}</div><button onclick="checkService('${s.id}')">Provjeri</button></div></div>`).join('')}</div></div>`}
async function checkService(id){try{const r=await api(`/api/services/${id}/actions/check`,{method:'POST',body:'{}'});alert(`${r.result.id}: ${r.result.status}\n${r.result.detail||''} (${r.result.latencyMs} ms)`);openModule(current)}catch(e){alert(e.message)}}
async function modulePage(id){const details={dns:['Zone i zapisi','U idućem milestoneu: forward/reverse zone, DNSSEC, ACL i validirani reload.'],dhcp:['Kea DHCP','Subneti, poolovi, rezervacije, KNOWN/UNKNOWN/DROP klase i quarantine politike.'],certificates:['Upravljanje certifikatima','Step CA za internu PKI te ACME/Let’s Encrypt za javne domene.'],proxy:['Nginx aplikacije','Deklarativni virtual hosts, TLS, WebSocket i rollback nakon nginx -t provjere.'],monitoring:['Monitoring','Servisi, resursi, DHCP poolovi, DNS greške i certifikati pred istekom.'],backup:['Backup','Šifrirane kopije, retention, provjera integriteta i restore test.'],users:['Korisnici i uloge','Planirane uloge: admin, network-operator, dns-operator, auditor i read-only.']}[id];$('#content').innerHTML=`<div class="panel"><h2>${details[0]}</h2><p class="muted">${details[1]}</p><p>Modul je registriran u GUI-ju; CRUD adapter dolazi u sljedećem koraku.</p></div>`}
async function monitoring(){const rows=await api('/api/events?limit=100');$('#content').innerHTML=`<div class="panel"><h2>Događaji (zadnjih ${rows.length})</h2><table><thead><tr><th>Vrijeme</th><th>Razina</th><th>Modul</th><th>Akcija</th><th>Poruka</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.ts).toLocaleString()}</td><td>${escapeHtml(x.severity)}</td><td>${escapeHtml(x.module)}</td><td>${escapeHtml(x.action||'')}</td><td>${escapeHtml(x.message)}</td></tr>`).join('')}</tbody></table></div>`}
async function mailPage(){const m=await api('/api/mail');const sev=['info','notice','warning','error','critical','security'];$('#content').innerHTML=`<div class="panel"><h2>SMTP postavke</h2><form id="mailForm" class="stack">
<label>Server <input id="mHost" value="${escapeHtml(m.host||'')}" placeholder="smtp.smtp2go.com" required></label>
<label>Port <input id="mPort" type="number" value="${m.port||587}" min="1" max="65535" required></label>
<label>TLS <select id="mTls">${['starttls','tls','none'].map(t=>`<option ${t===m.tlsMode?'selected':''}>${t}</option>`).join('')}</select></label>
<label>From <input id="mFrom" type="email" value="${escapeHtml(m.from||'')}" placeholder="sna@example.com" required></label>
<label>Korisničko ime <input id="mUser" value="${escapeHtml(m.username||'')}"></label>
<label>Lozinka <input id="mPass" type="password" placeholder="${m.hasPassword?'•••••• (nepromijenjeno)':''}"></label>
<label>Primatelji (zarezom) <input id="mRcpt" value="${escapeHtml((m.recipients||[]).join(', '))}" required></label>
<label>Minimalna razina za alarm <select id="mSev">${sev.map(s=>`<option ${s===m.minSeverity?'selected':''}>${s}</option>`).join('')}</select></label>
<label><input id="mEnabled" type="checkbox" ${m.enabled?'checked':''}> Alarmi uključeni</label>
<div><button type="submit">Spremi</button> <button type="button" id="mailTest">Test mail</button></div>
<p class="muted">Prvi događaj šalje se odmah; duplikati se agregiraju 10 minuta pa stiže sažetak. Preporuka: prije uključivanja alarma pošaljite test.</p>
<div id="mailMsg" class="muted"></div></form></div>`;
const payload=()=>({enabled:$('#mEnabled').checked,host:$('#mHost').value.trim(),port:parseInt($('#mPort').value,10),tlsMode:$('#mTls').value,from:$('#mFrom').value.trim(),username:$('#mUser').value.trim(),password:$('#mPass').value,recipients:$('#mRcpt').value.split(',').map(s=>s.trim()).filter(Boolean),minSeverity:$('#mSev').value});
$('#mailForm').onsubmit=async e=>{e.preventDefault();$('#mailMsg').textContent='';try{await api('/api/mail',{method:'PUT',body:JSON.stringify(payload())});$('#mailMsg').textContent='Spremljeno.';$('#mPass').value=''}catch(err){$('#mailMsg').textContent=err.message}};
$('#mailTest').onclick=async()=>{$('#mailMsg').textContent='Slanje testa…';try{await api('/api/mail',{method:'PUT',body:JSON.stringify(payload())});await api('/api/mail/test',{method:'POST',body:'{}'});$('#mailMsg').textContent='Test mail poslan — provjerite sandučić.'}catch(err){$('#mailMsg').textContent=err.message}}}
async function audit(){const rows=await api('/api/audit');$('#content').innerHTML=`<div class="panel"><table><thead><tr><th>Vrijeme</th><th>Razina</th><th>Korisnik</th><th>Akcija</th><th>Cilj</th><th>Rezultat</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.time).toLocaleString()}</td><td>${escapeHtml(x.severity||'info')}</td><td>${escapeHtml(x.actor)}</td><td>${escapeHtml(x.action)}</td><td>${escapeHtml(x.target)}</td><td>${escapeHtml(x.result)}</td></tr>`).join('')}</tbody></table></div>`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';showShell()}catch(err){$('#loginError').textContent=err.message}}
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}finally{showLogin()}}
api('/api/dashboard').then(showShell).catch(showLogin);
